# Generated by Django 4.2.30 on 2026-07-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0004_artigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
