# Generated by Django 4.2.30 on 2026-07-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0006_alter_artigo_options_alter_autor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artigos/'),
        ),
    ]
